#!/usr/bin/env python3
import csv, json
from collections import Counter
from pathlib import Path
from statistics import mean

ROOT=Path(__file__).resolve().parents[1]
TYPEA=ROOT/'data/typeA'
NM=TYPEA/'newsmaker_2003_outcomes_v0_3.json'
H21=TYPEA/'h21_2004_outcomes_v0_1.json'
DONGA=TYPEA/'donga_2010_post_t0_peak_master_v1_2.json'  # generated by final Dong-A builder in CI
OUTJ=TYPEA/'typeA_common_master_v0_1.json'
OUTC=TYPEA/'typeA_common_master_v0_1.csv'
OUTM=TYPEA/'typeA_common_metrics_v0_1.json'

def cls(delta, post):
    if delta>0: return 'advanced'
    if delta==0 and post>=3: return 'sustained_high'
    if delta==0: return 'no_clear_advancement'
    return 'lower_than_baseline'

def base_row(**kw):
    r={
      'person_id':f"ko:{kw['name']}",'name':kw['name'],'outlet':kw['outlet'],'selection_date':kw['selection_date'],
      'cohort_unit':kw['cohort_unit'],'list_title':kw['list_title'],'design':kw['design'],'domain':kw['domain'],
      'rank':kw.get('rank'),'rank_known':kw.get('rank') is not None,'target_horizon':kw.get('target_horizon'),
      'baseline_peak_through_t0':kw['baseline'],'post_t0_peak_score':kw['post'],'advancement_delta':kw['delta'],
      'advancement_class':kw['adv_class'],'major_ge3':kw['post']>=3,'apex_eq4':kw['post']==4,
      'death_truncated':kw.get('death_truncated'),'source_schema':kw['source_schema']
    }
    return r

def main():
    rows=[]
    nm=json.loads(NM.read_text(encoding='utf-8'))
    for p in nm['people']:
        domain=p['domain']; unit=f'newsmaker_2003_{domain}_top{10 if domain=="politics" else 5}'
        rows.append(base_row(
            name=p['name'],outlet='뉴스메이커',selection_date='2003-05-30',cohort_unit=unit,
            list_title='차세대 리더 정치·경제',design='ranked_topN_expert_survey',domain=domain,rank=p.get('rank'),
            baseline=p['baseline_peak_through_t0'],post=p['post_t0_peak_score'],delta=p['advancement_delta'],
            adv_class=p['baseline_adjusted_class'],source_schema='newsmaker_2003_outcomes_v0_3'
        ))
    h=json.loads(H21.read_text(encoding='utf-8'))
    for p in h['people']:
        rows.append(base_row(
            name=p['name'],outlet='한겨레21',selection_date='2004-09-20',cohort_unit='h21_2004_politics_top10',
            list_title='차세대 리더 여론조사 Top10',design='ranked_topN_public_opinion_survey',domain='politics',rank=p.get('rank'),
            baseline=p['baseline_peak_through_t0'],post=p['post_t0_peak_score'],delta=p['advancement_delta'],
            adv_class=p['baseline_adjusted_class'],source_schema='h21_2004_outcomes_v0_1'
        ))
    d=json.loads(DONGA.read_text(encoding='utf-8'))
    assert d['qa']['assessed']==100 and d['qa']['unresolved']==0
    for p in d['people']:
        rows.append(base_row(
            name=p['name'],outlet='동아일보',selection_date='2010-05-10',cohort_unit='donga_2010_2020_100',
            list_title='2020년 한국을 빛낼 100인',design='explicit_horizon_broad_screening',domain=p['category'],rank=None,
            target_horizon='2020',baseline=p['baseline_peak_through_t0'],post=p['post_t0_peak_score'],delta=p['advancement_delta'],
            adv_class=p['advancement_class'],death_truncated=p['exposure_truncated_by_death'],source_schema='donga_2010_post_t0_peak_master_v1_2'
        ))

    assert len(rows)==125
    people=Counter(r['person_id'] for r in rows)
    repeated={pid:n for pid,n in people.items() if n>1}
    assert len(people)==118, len(people)
    assert len(repeated)==7 and all(v==2 for v in repeated.values()), repeated
    repeated_names=sorted(pid.split(':',1)[1] for pid in repeated)
    assert set(repeated_names)=={'강금실','권영길','정동영','추미애','유시민','안철수','이재용'}

    units={}
    for unit in dict.fromkeys(r['cohort_unit'] for r in rows):
        rr=[r for r in rows if r['cohort_unit']==unit]
        units[unit]={
          'n':len(rr),'unique_people':len({r['person_id'] for r in rr}),'design':rr[0]['design'],'outlet':rr[0]['outlet'],
          'baseline_mean':mean(r['baseline_peak_through_t0'] for r in rr),
          'post_peak_mean':mean(r['post_t0_peak_score'] for r in rr),
          'major_n':sum(r['major_ge3'] for r in rr),'major_rate':sum(r['major_ge3'] for r in rr)/len(rr),
          'apex_n':sum(r['apex_eq4'] for r in rr),'apex_rate':sum(r['apex_eq4'] for r in rr)/len(rr),
          'advanced_n':sum(r['advancement_class']=='advanced' for r in rr),'advanced_rate':sum(r['advancement_class']=='advanced' for r in rr)/len(rr),
          'sustained_high_n':sum(r['advancement_class']=='sustained_high' for r in rr),
          'no_clear_advancement_n':sum(r['advancement_class']=='no_clear_advancement' for r in rr),
          'lower_than_baseline_n':sum(r['advancement_class']=='lower_than_baseline' for r in rr),
          'mean_delta':mean(r['advancement_delta'] for r in rr)
        }
    assert units['newsmaker_2003_politics_top10']['major_n']==10 and units['newsmaker_2003_politics_top10']['advanced_n']==7
    assert units['newsmaker_2003_economy_top5']['major_n']==5 and units['newsmaker_2003_economy_top5']['advanced_n']==4
    assert units['h21_2004_politics_top10']['major_n']==10 and units['h21_2004_politics_top10']['advanced_n']==4
    assert units['donga_2010_2020_100']['major_n']==71 and units['donga_2010_2020_100']['advanced_n']==28

    small=[r for r in rows if r['design'].startswith('ranked_topN')]
    broad=[r for r in rows if r['design']=='explicit_horizon_broad_screening']
    naive={
      'placements':125,'unique_people':118,'major_n':sum(r['major_ge3'] for r in rows),'major_rate':sum(r['major_ge3'] for r in rows)/125,
      'apex_n':sum(r['apex_eq4'] for r in rows),'apex_rate':sum(r['apex_eq4'] for r in rows)/125,
      'advanced_n':sum(r['advancement_class']=='advanced' for r in rows),'advanced_rate':sum(r['advancement_class']=='advanced' for r in rows)/125,
      'warning':'Descriptive only: repeated persons and heterogeneous list designs make naive pooled inferential interpretation invalid.'
    }
    assert (naive['major_n'],naive['apex_n'],naive['advanced_n'])==(96,23,43)
    design_summary={
      'ranked_topN_units':{'placements':len(small),'unique_people':len({r['person_id'] for r in small}),'major_n':sum(r['major_ge3'] for r in small),'major_rate':sum(r['major_ge3'] for r in small)/len(small),'apex_n':sum(r['apex_eq4'] for r in small),'apex_rate':sum(r['apex_eq4'] for r in small)/len(small),'advanced_n':sum(r['advancement_class']=='advanced' for r in small),'advanced_rate':sum(r['advancement_class']=='advanced' for r in small)/len(small)},
      'broad_explicit_horizon':{'placements':len(broad),'unique_people':len({r['person_id'] for r in broad}),'major_n':sum(r['major_ge3'] for r in broad),'major_rate':sum(r['major_ge3'] for r in broad)/len(broad),'apex_n':sum(r['apex_eq4'] for r in broad),'apex_rate':sum(r['apex_eq4'] for r in broad)/len(broad),'advanced_n':sum(r['advancement_class']=='advanced' for r in broad),'advanced_rate':sum(r['advancement_class']=='advanced' for r in broad)/len(broad)},
      'warning':'This is design-stratified description, not an outlet effect estimate. Domain, list depth, year, and selection mechanism are confounded.'
    }
    assert design_summary['ranked_topN_units']['placements']==25 and design_summary['ranked_topN_units']['unique_people']==21
    assert (design_summary['ranked_topN_units']['major_n'],design_summary['ranked_topN_units']['apex_n'],design_summary['ranked_topN_units']['advanced_n'])==(25,11,15)

    master={'schema_version':'typeA_common_master_v0.1','generated':'2026-08-18','status':'descriptive_common_master_first_125_placements','qa':{'placements':125,'unique_people':118,'repeated_person_n':7,'repeated_names':repeated_names,'cohort_units':4},'rows':rows}
    metrics={'schema_version':'typeA_common_metrics_v0.1','generated':'2026-08-18','master_runtime_ref':'data/typeA/typeA_common_master_v0_1.json','qa':master['qa'],'by_cohort_unit':units,'naive_pooled_descriptive':naive,'by_design':design_summary,'interpretation_guardrails':['Do not treat 125 placements as independent observations; seven people appear twice.','Do not compare ranked TopN and broad 100-person screening as if list depth/design were equivalent.','Baseline-adjusted advancement is the preferred outcome for future-rise claims; major attainment includes sustained already-high selections.','Rank analysis is only meaningful for units with an actual published rank.']}
    OUTJ.write_text(json.dumps(master,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    OUTM.write_text(json.dumps(metrics,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    fields=['person_id','name','outlet','selection_date','cohort_unit','list_title','design','domain','rank','rank_known','target_horizon','baseline_peak_through_t0','post_t0_peak_score','advancement_delta','advancement_class','major_ge3','apex_eq4','death_truncated','source_schema']
    with OUTC.open('w',encoding='utf-8-sig',newline='') as f:
        w=csv.DictWriter(f,fieldnames=fields);w.writeheader();w.writerows({k:r.get(k) for k in fields} for r in rows)
    print(json.dumps(metrics,ensure_ascii=False,indent=2))

if __name__=='__main__': main()
